# -*- coding: utf-8 -*-
"""Coffie mission using python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J9YKAUBTT3CmlTuD3sDSwlNaXhU50nPQ
"""

MENU = {
    "espresso": {
        "ingredients": {"water": 50, "milk": 0, "coffee": 20},
        "cost": 80
    },
    "latte": {
        "ingredients": {"water": 200, "milk": 150, "coffee": 25},
        "cost": 200
    },
    "cappuccino": {
        "ingredients": {"water": 250, "milk": 100, "coffee": 30},
        "cost": 150
    }
}

resources = {
    "water": 30000,
    "milk": 20000,
    "coffee": 10000,
    "money": 0.0
}

def report():
    print(f"Water: {resources['water']}ml")
    print(f"Milk: {resources['milk']}ml")
    print(f"Coffee: {resources['coffee']}g")
    print(f"Money: ₹{resources['money']}")

def is_resource_sufficient(order_ingredients):
    for item in order_ingredients:
        if order_ingredients[item] > resources[item]:
            print(f"Sorry, not enough {item}.")
            return False
    return True

def process_payment(drink_cost):
    amount_received = float(input("Insert money in ₹: "))
    if amount_received < drink_cost:
        print("Sorry, that's not enough money. Money refunded.")
        return False
    change = round(amount_received - drink_cost, 2)
    if change > 0:
        print(f"Here is ₹{change} in change.")
    resources["money"] += drink_cost
    return True

def make_coffee(drink_name, order_ingredients):
    for item in order_ingredients:
        resources[item] -= order_ingredients[item]
    print(f"Here is your {drink_name}. Enjoy!")

# Main Loop
is_on = True

while is_on:
    choice = input("What would you like? (espresso/latte/cappuccino/report/off): ").lower()
    if choice == "off":
        is_on = False
    elif choice == "report":
        report()
    elif choice in MENU:
        drink = MENU[choice]
        if is_resource_sufficient(drink["ingredients"]):
            if process_payment(drink["cost"]):
                make_coffee(choice, drink["ingredients"])
    else:
        print("Invalid choice.")