# -*- coding: utf-8 -*-
"""Simple Calculator using python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J9YKAUBTT3CmlTuD3sDSwlNaXhU50nPQ
"""

def add(a,b):
    return a + b
def subaract(a,b):
    return a - b
def multiple(a,b):
    return a * b
def div(a,b):
    return a / b
def cal(a,b,z):
    if z == 1:
        print(add(a,b))
    elif z == 2:
        print(subaract(a,b))
    elif z == 3:
        print(multiple(a,b))
    elif z == 4:
        print(div(a,b))
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
print("enter 1 to add \n emter 2 to subract \n enter 3 to multiple \n enter 4 to divided \n" )
z=int(input("enter oprater"))
cal(a,b,z)